import streamlit as st
import requests

BASE_URL = "http://127.0.0.1:8000"

st.set_page_config(page_title="AI MongoDB Agent", layout="wide")
st.title("AI MongoDB Agent 🧠📊")

menu = ["Add Person", "View All Persons", "AI Query"]
choice = st.sidebar.selectbox("Menu", menu)

# ------------------ ADD PERSON ------------------ #
if choice == "Add Person":
    st.subheader("Add a New Person")
    name = st.text_input("Name")
    age = st.number_input("Age", min_value=0, max_value=120, step=1)

    if st.button("Add"):
        if not name:
            st.warning("Please enter a name")
        else:
            payload = {"name": name, "age": age}
            response = requests.post(f"{BASE_URL}/persons/create", json=payload)
            if response.status_code == 200:
                st.success(f"Person added with ID: {response.json()['id']}")
            else:
                st.error("Error adding person")

# ------------------ VIEW ALL PERSONS ------------------ #
elif choice == "View All Persons":
    st.subheader("All Persons in Database")
    response = requests.get(f"{BASE_URL}/persons/")
    if response.status_code == 200:
        persons = response.json()
        if persons:
            st.table(persons)
        else:
            st.info("No persons found")
    else:
        st.error("Error fetching persons")

# ------------------ AI QUERY ------------------ #
elif choice == "AI Query":
    st.subheader("Ask AI to Query Persons")
    user_query = st.text_area("Enter your query (e.g., find a person with name Bilal, age > 20)")

    if st.button("Run AI Query"):
        if not user_query.strip():
            st.warning("Please type a query")
        else:
            response = requests.post(f"{BASE_URL}/AI/query_person", params={"user_query": user_query})
            if response.status_code == 200:
                data = response.json()
                st.write("**Mongo Filter Generated by AI:**")
                st.json(data["mongo_filter"])
                st.write("**Query Result:**")
                st.table(data["result"])
            else:
                st.error(f"Error: {response.status_code} - {response.text}")
